apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kibana
  namespace: kube-efk
  labels:
    k8s-app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
    spec:
      volumes:
      - name: kibana-conf
        configMap:
          name: kibana-configmap
      - name: host-time
        hostPath:
          path: /etc/localtime
      containers:
      - name: kibana
        image: h3crd-wlan1.chinacloudapp.cn:5000/kibana_zj:5.6.4
        livenessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 600
          timeoutSeconds: 5
          periodSeconds: 180
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 1
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        volumeMounts:
        - name: kibana-conf
          mountPath: /usr/share/kibana/config
        - name: host-time
          mountPath: /etc/localtime
