apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-efk
  labels:
    k8s-app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
    nodePort: 56001
  selector:
    k8s-app: kibana