apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-efk
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: es-1
  - port: 9300
    name: es-2
  selector:
    app: elasticsearch

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: kube-efk
spec:
  serviceName: "elasticsearch"
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeSelector:
        es: elasticsearch
      volumes:
      - name: es-config
        configMap:
          name: es-configmap
      - name: host-time
        hostPath:
          path: /etc/localtime
      hostNetwork: true
      containers:
      - name: esc
        image: h3crd-wlan1.chinacloudapp.cn:5000/elasticsearch-v1:5.6.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: es-1
          containerPort: 9200
        - name: es-2
          containerPort: 9300
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: elasticsearch-cluster
        volumeMounts:
       # - name: es-datadir
       #   mountPath: /data
        - name: es-config
          mountPath: /usr/share/elasticsearch/config
        securityContext:
          capabilities: {}
          privileged: true
#  volumeClaimTemplates:
#  - metadata:
#      name: es-datadir
#      annotations:
#        volume.beta.kubernetes.io/storage-class: "fast"
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      resources:
#        requests:
#          storage: 1Gi
