apiVersion: v1
kind: Service
metadata:
  name: es-head
  labels:
    app: es-head
spec:
  type: NodePort
  ports:
  - nodePort: 20210
    port: 9100
    name: port1
  selector:
    app: es-head

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-head
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: es-head
    spec:
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      containers:
      - name: eshead
        image: h3crd-wlan1.chinacloudapp.cn:5000/es-head-1350:v0709
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9100
          name: port1
        env:
        - name: elasticsearch_host
          value: "172.20.0.36:9200"
        securityContext:
          capabilities: {}
          privileged: true
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime